name: flutter_lab_final
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  supabase_flutter: ^2.6.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_fonts: ^6.3.3
  flutter_staggered_grid_view: ^0.7.0
  uuid: ^4.5.2
  http: ^1.6.0
  animated_login: ^1.7.2
  image_picker: ^1.2.1
  image_cropper: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
